spring:
  main:
    # 此处为reactive
    web-application-type: reactive
    banner-mode: off
    allow-bean-definition-overriding: true
  ai:
    mcp:
      server:
        name: webflux-weather-server
        version: 1.0.0
        type: ASYNC
        sse-message-endpoint: /mcp/messages

server:
  port: 8081

weather:
  api:
    key: your-api-key-here
    base-url: https://api.openweathermap.org