spring:
  main:
    # 此处为reactive
    web-application-type: none
    banner-mode: off
    allow-bean-definition-overriding: true
  ai:
    openai:
      api-key: "your api key"
      base-url: "your base url"
      chat:
        options:
          model: "gpt-4o"
          temperature: 0.2
    mcp:
      client:
        sse:
          connections:
            device-server:
              url: http://localhost:8082
        toolcallback:
          enabled: true
server:
  port: 8083
